//! Authoritative portable editor field schema and generated-adapter property mapping.
use serde::Serialize;
#[derive(Clone, Copy, Serialize)]
pub struct Field {
    pub key: &'static str,
    pub kind: &'static str,
    pub default: &'static str,
    pub cs: &'static str,
    pub kotlin: &'static str,
    pub swift: &'static str,
}
macro_rules! field {
    ($key:literal, $kind:literal, $default:literal, $cs:literal, $kt:literal, $sw:literal) => {
        Field {
            key: $key,
            kind: $kind,
            default: $default,
            cs: $cs,
            kotlin: $kt,
            swift: $sw,
        }
    };
}
#[rustfmt::skip]
pub const FIELDS: &[Field] = &[
    field!("server", "string", "", "ServerAddress", "serverAddress", "serverAddress"),
    field!("name", "string", "", "Name", "-", "-"),
    field!("proto", "string", "tcp", "Protocol", "protocol", "protocolName"),
    field!("user", "string", "client", "Username", "username", "username"),
    field!("pass", "string", "", "Password", "password", "password"),
    field!("key", "string", "", "ServerPublicKeyHex", "serverPublicKeyHex", "serverPublicKeyHex"),
    field!("bind_static", "bool", "true", "BindStaticToSession", "bindStaticToSession", "bindStaticToSession"),
    field!("allow_unpinned_tofu", "bool", "false", "AllowUnpinnedTofu", "allowUnpinnedTofu", "allowUnpinnedTofu"),
    field!("mode", "string", "fake-tls", "WireMode", "wireMode", "wireMode"),
    field!("obfs_key", "string", "", "ObfsKey", "obfsKey", "obfsKey"),
    field!("front", "string", "websocket", "ObfsFronting", "obfsFronting", "obfsFronting"),
    field!("sni", "string", "", "Sni", "sni", "sni"),
    field!("reality_sid", "string", "", "RealityShortId", "realityShortId", "realityShortID"),
    field!("quic", "bool", "false", "QuicEnabled", "quicEnabled", "quicEnabled"),
    field!("awg", "bool", "false", "AwgEnabled", "awgEnabled", "awgEnabled"),
    field!("jc", "int", "0", "AwgJc", "awgJc", "awgJunkCount"),
    field!("jmin", "int", "40", "AwgJmin", "awgJmin", "awgJunkMin"),
    field!("jmax", "int", "300", "AwgJmax", "awgJmax", "awgJunkMax"),
    field!("mtu", "int", "0", "Mtu", "mtu", "mtu"),
    field!("mtu_probe", "bool", "true", "MtuProbe", "mtuProbe", "mtuProbe"),
    field!("gateway", "bool", "true", "AddDefaultGateway", "addDefaultGateway", "addDefaultGateway"),
    field!("ipv6", "string", "auto", "Ipv6Policy", "ipv6", "ipv6Policy"),
    field!("roaming", "string", "auto", "RoamingPolicy", "roaming", "roamingPolicy"),
    field!("route_local", "bool", "false", "RouteLocalNetworks", "routeLocalNetworks", "routeLocalNetworks"),
    field!("kill_switch", "bool", "false", "KillSwitch", "killSwitch", "-"),
    field!("allow_ipv4_leak", "bool", "false", "AllowIpv4Leak", "allowIpv4Leak", "allowIPv4Leak"),
    field!("allow_ipv6_leak", "bool", "false", "AllowIpv6Leak", "allowIpv6Leak", "allowIPv6Leak"),
    field!("allow_lan", "bool", "false", "-", "allowLan", "allowLAN"),
    field!("include", "list", "", "IncludeRoutes", "includeRoutes", "includeRoutes"),
    field!("exclude", "list", "", "ExcludeRoutes", "excludeRoutes", "excludeRoutes"),
    field!("dns", "string", "tunnel", "DnsMode", "dnsMode", "dnsMode"),
    field!("dns_servers", "list", "", "DnsServers", "dnsServers", "dnsServers"),
    field!("apps_mode", "string", "all", "AppsMode", "appsMode", "appsMode"),
    field!("apps", "list", "", "Apps", "apps", "apps"),
    field!("route_file", "lines", "", "RouteFilePaths", "routeFiles", "routeFiles"),
    field!("persist_tun", "bool", "false", "PersistTun", "-", "-"),
    field!("forward", "bool", "false", "Forward", "-", "-"),
    field!("local", "string", "", "LocalAddress", "-", "-"),
    field!("lport", "int", "0", "LocalPort", "-", "-"),
    field!("metric", "int", "0", "InterfaceMetric", "-", "-"),
    field!("dev_node", "string", "", "DevNode", "-", "-"),
    field!("dev", "string", "vpn0", "-", "-", "-"),
    field!("device_type", "string", "tun", "-", "-", "-"),
    field!("dev_attach", "bool", "false", "-", "-", "-"),
    field!("autostart", "bool", "false", "-", "-", "-"),
    field!("exit_node", "bool", "false", "-", "-", "-"),
    field!("gateway_nat", "bool", "false", "-", "-", "-"),
    field!("lan_subnet", "string", "", "-", "-", "-"),
    field!("lan_subnet_ipv6", "string", "", "-", "-", "-"),
    field!("post_up", "string", "", "-", "-", "-"),
    field!("post_down", "string", "", "-", "-", "-"),
    field!("password_file", "string", "", "-", "-", "-"),
    field!("password_command", "string", "", "-", "-", "-"),
    field!("keepalive", "int", "60", "-", "-", "-"),
    field!("tcp_nodelay", "bool", "true", "-", "-", "-"),
    field!("recv_buffer_size", "int", "4194304", "-", "-", "-"),
    field!("send_buffer_size", "int", "0", "-", "-", "-"),
    field!("reality_compact", "bool", "false", "-", "-", "-"),
    field!("reality_split", "string", "", "-", "-", "-"),
    field!("reality_split_delay", "int", "100", "-", "-", "-"),
    field!("reconnect", "bool", "true", "ReconnectEnabled", "reconnectEnabled", "reconnectEnabled"),
    field!("reconnect_retries", "int", "-1", "ReconnectMaxRetries", "reconnectMaxRetries", "reconnectMaxRetries"),
    field!("reconnect_base_delay", "int", "1", "ReconnectBaseDelaySecs", "reconnectBaseDelaySecs", "reconnectBaseDelaySeconds"),
    field!("reconnect_max_delay", "int", "60", "ReconnectMaxDelaySecs", "reconnectMaxDelaySecs", "reconnectMaxDelaySeconds"),
    field!("timeout", "int", "30", "ConnectionTimeoutSecs", "connectionTimeoutSecs", "connectionTimeoutSeconds"),
    field!("padding", "bool", "true", "PaddingEnabled", "paddingEnabled", "paddingEnabled"),
    field!("padding_min", "int", "0", "PaddingMin", "paddingMin", "paddingMin"),
    field!("padding_max", "int", "255", "PaddingMax", "paddingMax", "paddingMax"),
    field!("heartbeat", "bool", "true", "HeartbeatEnabled", "heartbeatEnabled", "heartbeatEnabled"),
    field!("heartbeat_interval", "int", "15000", "HeartbeatIntervalMs", "heartbeatIntervalMs", "heartbeatIntervalMilliseconds"),
    field!("heartbeat_size", "int", "16", "HeartbeatDataSize", "heartbeatDataSize", "heartbeatDataSize"),
    field!("heartbeat_jitter", "int", "2000", "HeartbeatJitterMs", "heartbeatJitterMs", "heartbeatJitterMilliseconds"),
    field!("shaping", "bool", "false", "ShapingEnabled", "shapingEnabled", "shapingEnabled"),
    field!("shaping_gap_mean", "int", "700", "ShapingGapMeanMs", "shapingGapMeanMs", "shapingGapMeanMilliseconds"),
    field!("shaping_gap_min", "int", "40", "ShapingGapMinMs", "shapingGapMinMs", "shapingGapMinMilliseconds"),
    field!("shaping_gap_max", "int", "6000", "ShapingGapMaxMs", "shapingGapMaxMs", "shapingGapMaxMilliseconds"),
    field!("shaping_budget", "int", "16384", "ShapingBudgetBytesPerSec", "shapingBudgetBytesPerSec", "shapingBudgetBytesPerSecond"),
    field!("shaping_min_size", "int", "64", "ShapingMinSize", "shapingMinSize", "shapingMinSize"),
    field!("shaping_max_size", "int", "1024", "ShapingMaxSize", "shapingMaxSize", "shapingMaxSize"),
    field!("shaping_stealth", "bool", "false", "ShapingStealth", "shapingStealth", "shapingStealth"),
    field!("shaping_stealth_mbps", "int", "2", "ShapingStealthRateMbps", "shapingStealthRateMbps", "shapingStealthRateMbps"),
    field!("logging.level", "string", "info", "LoggingLevel", "loggingLevel", "loggingLevel"),
    field!("logging.file", "string", "", "-", "loggingFile", "loggingFile"),
    field!("logging.time_format", "string", "datetime", "-", "loggingTimeFormat", "loggingTimeFormat"),
];

/// Credential values must never appear in diagnostic messages.
pub fn sensitive(key: &str) -> bool {
    matches!(
        key,
        "pass" | "password_command" | "obfs_key" | "reality_sid"
    )
}
