// Generated by scripts/gen_config_bindings.py; change the Rust schema.
#nullable enable
using System.Text.Json;
namespace Qeli.Shared.Model;
public sealed partial class VpnConfig {
    private static readonly HashSet<string> NativeCarriedKeys = new() { "allow_lan","dev","device_type","dev_attach","autostart","exit_node","gateway_nat","lan_subnet","lan_subnet_ipv6","post_up","post_down","password_file","password_command","keepalive","tcp_nodelay","recv_buffer_size","send_buffer_size","reality_compact","reality_split","reality_split_delay" };
    private Dictionary<string, object?> NativeValues() => new() {
        ["$host"] = ServerAddress, ["$port"] = Port, ["$routing_mode"] = RoutingMode,
        ["name"] = Name ?? "",
        ["proto"] = Protocol ?? "",
        ["user"] = Username ?? "",
        ["pass"] = Password ?? "",
        ["key"] = ServerPublicKeyHex ?? "",
        ["bind_static"] = BindStaticToSession,
        ["allow_unpinned_tofu"] = AllowUnpinnedTofu,
        ["mode"] = WireMode ?? "",
        ["obfs_key"] = ObfsKey ?? "",
        ["front"] = ObfsFronting ?? "",
        ["sni"] = Sni ?? "",
        ["reality_sid"] = RealityShortId ?? "",
        ["quic"] = QuicEnabled,
        ["awg"] = AwgEnabled,
        ["jc"] = AwgJc,
        ["jmin"] = AwgJmin,
        ["jmax"] = AwgJmax,
        ["mtu"] = Mtu,
        ["mtu_probe"] = MtuProbe,
        ["gateway"] = AddDefaultGateway,
        ["ipv6"] = Ipv6Policy ?? "",
        ["roaming"] = RoamingPolicy ?? "",
        ["route_local"] = RouteLocalNetworks,
        ["kill_switch"] = KillSwitch,
        ["allow_ipv4_leak"] = AllowIpv4Leak,
        ["allow_ipv6_leak"] = AllowIpv6Leak,
        ["include"] = IncludeRoutes,
        ["exclude"] = ExcludeRoutes,
        ["dns"] = DnsMode ?? "",
        ["dns_servers"] = DnsServers,
        ["apps_mode"] = AppsMode ?? "",
        ["apps"] = Apps,
        ["route_file"] = RouteFile is null ? AdditionalRouteFiles.ToArray() : new[] { RouteFile }.Concat(AdditionalRouteFiles).ToArray(),
        ["persist_tun"] = PersistTun,
        ["forward"] = Forward,
        ["local"] = LocalAddress ?? "",
        ["lport"] = LocalPort,
        ["metric"] = InterfaceMetric,
        ["dev_node"] = DevNode ?? "",
        ["reconnect"] = ReconnectEnabled,
        ["reconnect_retries"] = ReconnectMaxRetries,
        ["reconnect_base_delay"] = ReconnectBaseDelaySecs,
        ["reconnect_max_delay"] = ReconnectMaxDelaySecs,
        ["timeout"] = ConnectionTimeoutSecs,
        ["padding"] = PaddingEnabled,
        ["padding_min"] = PaddingMin,
        ["padding_max"] = PaddingMax,
        ["heartbeat"] = HeartbeatEnabled,
        ["heartbeat_interval"] = HeartbeatIntervalMs,
        ["heartbeat_size"] = HeartbeatDataSize,
        ["heartbeat_jitter"] = HeartbeatJitterMs,
        ["shaping"] = ShapingEnabled,
        ["shaping_gap_mean"] = ShapingGapMeanMs,
        ["shaping_gap_min"] = ShapingGapMinMs,
        ["shaping_gap_max"] = ShapingGapMaxMs,
        ["shaping_budget"] = ShapingBudgetBytesPerSec,
        ["shaping_min_size"] = ShapingMinSize,
        ["shaping_max_size"] = ShapingMaxSize,
        ["shaping_stealth"] = ShapingStealth,
        ["shaping_stealth_mbps"] = ShapingStealthRateMbps,
        ["logging.level"] = LoggingLevel ?? "",
    };
    private JsonElement NativeOperation(string operation) {
        var values = NativeValues();
        foreach (var entry in CarriedKeys) values[entry.Key] = entry.Value;
        return ConfigCore.Call(new { version=1, op=operation, source=NativeSource, values, unresolved=UnparsedBooleanKeys.Concat(UnparsedNumericKeys).ToArray() });
    }
    private static VpnConfig NativeImport(string text) {
        var result = ConfigCore.Call(new { version=1, op="import", source=text });
        var v = result.GetProperty("values");
        var diagnostics = result.GetProperty("diagnostics").EnumerateArray().ToArray();
        string[] Keys(string code) => diagnostics.Where(d => d.GetProperty("code").GetString() == code).Select(d => d.GetProperty("key").GetString()!).ToArray();
        return new VpnConfig { NativeSource=result.GetProperty("source").GetString(), ServerAddress=v.GetProperty("$host").GetString()!, Port=v.GetProperty("$port").GetInt32(),
            Name = v.GetProperty("name").Deserialize<string?>()!,
            Protocol = v.GetProperty("proto").Deserialize<string>()!,
            Username = v.GetProperty("user").Deserialize<string>()!,
            Password = v.GetProperty("pass").Deserialize<string>()!,
            ServerPublicKeyHex = (v.GetProperty("key").GetString() is { Length: > 0 } ServerPublicKeyHexValue ? ServerPublicKeyHexValue : null),
            BindStaticToSession = v.GetProperty("bind_static").Deserialize<bool>()!,
            AllowUnpinnedTofu = v.GetProperty("allow_unpinned_tofu").Deserialize<bool>()!,
            WireMode = v.GetProperty("mode").Deserialize<string>()!,
            ObfsKey = v.GetProperty("obfs_key").Deserialize<string>()!,
            ObfsFronting = v.GetProperty("front").Deserialize<string>()!,
            Sni = (v.GetProperty("sni").GetString() is { Length: > 0 } SniValue ? SniValue : null),
            RealityShortId = (v.GetProperty("reality_sid").GetString() is { Length: > 0 } RealityShortIdValue ? RealityShortIdValue : null),
            QuicEnabled = v.GetProperty("quic").Deserialize<bool>()!,
            AwgEnabled = v.GetProperty("awg").Deserialize<bool>()!,
            AwgJc = v.GetProperty("jc").Deserialize<uint>()!,
            AwgJmin = v.GetProperty("jmin").Deserialize<ushort>()!,
            AwgJmax = v.GetProperty("jmax").Deserialize<ushort>()!,
            Mtu = v.GetProperty("mtu").Deserialize<int>()!,
            MtuProbe = v.GetProperty("mtu_probe").Deserialize<bool>()!,
            AddDefaultGateway = v.GetProperty("gateway").Deserialize<bool>()!,
            Ipv6Policy = v.GetProperty("ipv6").Deserialize<string>()!,
            RoamingPolicy = v.GetProperty("roaming").Deserialize<string>()!,
            RouteLocalNetworks = v.GetProperty("route_local").Deserialize<bool>()!,
            KillSwitch = v.GetProperty("kill_switch").Deserialize<bool>()!,
            AllowIpv4Leak = v.GetProperty("allow_ipv4_leak").Deserialize<bool>()!,
            AllowIpv6Leak = v.GetProperty("allow_ipv6_leak").Deserialize<bool>()!,
            IncludeRoutes = v.GetProperty("include").Deserialize<List<string>>()!,
            ExcludeRoutes = v.GetProperty("exclude").Deserialize<List<string>>()!,
            DnsMode = v.GetProperty("dns").Deserialize<string>()!,
            DnsServers = v.GetProperty("dns_servers").Deserialize<List<string>>()!,
            AppsMode = v.GetProperty("apps_mode").Deserialize<string>()!,
            Apps = v.GetProperty("apps").Deserialize<List<string>>()!,
            RouteFile=v.GetProperty("route_file").EnumerateArray().Select(x=>x.GetString()).FirstOrDefault(),
            AdditionalRouteFiles=v.GetProperty("route_file").EnumerateArray().Skip(1).Select(x=>x.GetString()!).ToList(),
            PersistTun = v.GetProperty("persist_tun").Deserialize<bool>()!,
            Forward = v.GetProperty("forward").Deserialize<bool>()!,
            LocalAddress = (v.GetProperty("local").GetString() is { Length: > 0 } LocalAddressValue ? LocalAddressValue : null),
            LocalPort = v.GetProperty("lport").Deserialize<int>()!,
            InterfaceMetric = v.GetProperty("metric").Deserialize<int>()!,
            DevNode = (v.GetProperty("dev_node").GetString() is { Length: > 0 } DevNodeValue ? DevNodeValue : null),
            ReconnectEnabled = v.GetProperty("reconnect").Deserialize<bool>()!,
            ReconnectMaxRetries = v.GetProperty("reconnect_retries").Deserialize<int>()!,
            ReconnectBaseDelaySecs = v.GetProperty("reconnect_base_delay").Deserialize<long>()!,
            ReconnectMaxDelaySecs = v.GetProperty("reconnect_max_delay").Deserialize<long>()!,
            ConnectionTimeoutSecs = v.GetProperty("timeout").Deserialize<long>()!,
            PaddingEnabled = v.GetProperty("padding").Deserialize<bool>()!,
            PaddingMin = v.GetProperty("padding_min").Deserialize<int>()!,
            PaddingMax = v.GetProperty("padding_max").Deserialize<int>()!,
            HeartbeatEnabled = v.GetProperty("heartbeat").Deserialize<bool>()!,
            HeartbeatIntervalMs = v.GetProperty("heartbeat_interval").Deserialize<long>()!,
            HeartbeatDataSize = v.GetProperty("heartbeat_size").Deserialize<int>()!,
            HeartbeatJitterMs = v.GetProperty("heartbeat_jitter").Deserialize<long>()!,
            ShapingEnabled = v.GetProperty("shaping").Deserialize<bool>()!,
            ShapingGapMeanMs = v.GetProperty("shaping_gap_mean").Deserialize<long>()!,
            ShapingGapMinMs = v.GetProperty("shaping_gap_min").Deserialize<long>()!,
            ShapingGapMaxMs = v.GetProperty("shaping_gap_max").Deserialize<long>()!,
            ShapingBudgetBytesPerSec = v.GetProperty("shaping_budget").Deserialize<int>()!,
            ShapingMinSize = v.GetProperty("shaping_min_size").Deserialize<int>()!,
            ShapingMaxSize = v.GetProperty("shaping_max_size").Deserialize<int>()!,
            ShapingStealth = v.GetProperty("shaping_stealth").Deserialize<bool>()!,
            ShapingStealthRateMbps = v.GetProperty("shaping_stealth_mbps").Deserialize<int>()!,
            LoggingLevel = v.GetProperty("logging.level").Deserialize<string>()!,
            RoutingMode=v.GetProperty("gateway").GetBoolean() ? "full-tunnel" : "split-tunnel",
            UnparsedBooleanKeys=Keys("bool"), UnparsedNumericKeys=Keys("int"), UnknownKeys=Keys("unknown"),
            DuplicateKeys=Keys("duplicate").Concat(Keys("section")).ToArray(),
            CarriedKeys=result.GetProperty("raw").EnumerateObject().Where(p=>NativeCarriedKeys.Contains(p.Name)).ToDictionary(p=>p.Name,p=>p.Value[0].GetString()!),
            InvalidRawValues=result.GetProperty("raw").EnumerateObject().Where(p=>diagnostics.Any(d=>d.GetProperty("key").GetString()==p.Name)).ToDictionary(p=>p.Name,p=>p.Value[0].GetString()!),
        };
    }
}

internal static class ConfigDefaults {
    public const string? Name = null;
    public const string Protocol = "tcp";
    public const string Username = "client";
    public const string Password = "";
    public const string? ServerPublicKeyHex = null;
    public const bool BindStaticToSession = true;
    public const bool AllowUnpinnedTofu = false;
    public const string WireMode = "fake-tls";
    public const string ObfsKey = "";
    public const string ObfsFronting = "websocket";
    public const string? Sni = null;
    public const string? RealityShortId = null;
    public const bool QuicEnabled = false;
    public const bool AwgEnabled = false;
    public const uint AwgJc = 0;
    public const ushort AwgJmin = 40;
    public const ushort AwgJmax = 300;
    public const int Mtu = 0;
    public const bool MtuProbe = true;
    public const bool AddDefaultGateway = true;
    public const string Ipv6Policy = "auto";
    public const string RoamingPolicy = "auto";
    public const bool RouteLocalNetworks = false;
    public const bool KillSwitch = false;
    public const bool AllowIpv4Leak = false;
    public const bool AllowIpv6Leak = false;
    public const string DnsMode = "tunnel";
    public const string AppsMode = "all";
    public const bool PersistTun = false;
    public const bool Forward = false;
    public const string? LocalAddress = null;
    public const int LocalPort = 0;
    public const int InterfaceMetric = 0;
    public const string? DevNode = null;
    public const bool ReconnectEnabled = true;
    public const int ReconnectMaxRetries = -1;
    public const long ReconnectBaseDelaySecs = 1;
    public const long ReconnectMaxDelaySecs = 60;
    public const long ConnectionTimeoutSecs = 30;
    public const bool PaddingEnabled = true;
    public const int PaddingMin = 0;
    public const int PaddingMax = 255;
    public const bool HeartbeatEnabled = true;
    public const long HeartbeatIntervalMs = 15000;
    public const int HeartbeatDataSize = 16;
    public const long HeartbeatJitterMs = 2000;
    public const bool ShapingEnabled = false;
    public const long ShapingGapMeanMs = 700;
    public const long ShapingGapMinMs = 40;
    public const long ShapingGapMaxMs = 6000;
    public const int ShapingBudgetBytesPerSec = 16384;
    public const int ShapingMinSize = 64;
    public const int ShapingMaxSize = 1024;
    public const bool ShapingStealth = false;
    public const int ShapingStealthRateMbps = 2;
    public const string LoggingLevel = "info";
}
