// Generated by scripts/gen_config_bindings.py; change the Rust schema.
import Foundation
extension VPNConfig {
    static let carriedINIKeys: Set<String> = ["name","kill_switch","persist_tun","forward","local","lport","metric","dev_node","dev","device_type","dev_attach","autostart","exit_node","gateway_nat","lan_subnet","lan_subnet_ipv6","post_up","post_down","password_file","password_command","keepalive","tcp_nodelay","recv_buffer_size","send_buffer_size","reality_compact","reality_split","reality_split_delay"]
    func nativeOperation(_ op: String, label: String? = nil) throws -> [String: Any] {
        var values: [String: Any] = ["$host":serverAddress, "$port":port,
            "proto":protocolName,
            "user":username,
            "pass":password,
            "key":serverPublicKeyHex ?? "",
            "bind_static":bindStaticToSession,
            "allow_unpinned_tofu":allowUnpinnedTofu,
            "mode":wireMode,
            "obfs_key":obfsKey,
            "front":obfsFronting,
            "sni":sni ?? "",
            "reality_sid":realityShortID ?? "",
            "quic":quicEnabled,
            "awg":awgEnabled,
            "jc":awgJunkCount,
            "jmin":awgJunkMin,
            "jmax":awgJunkMax,
            "mtu":mtu,
            "mtu_probe":mtuProbe,
            "gateway":addDefaultGateway,
            "ipv6":ipv6Policy,
            "roaming":roamingPolicy,
            "route_local":routeLocalNetworks,
            "allow_ipv4_leak":allowIPv4Leak,
            "allow_ipv6_leak":allowIPv6Leak,
            "allow_lan":allowLAN,
            "include":includeRoutes,
            "exclude":excludeRoutes,
            "dns":dnsMode,
            "dns_servers":dnsServers,
            "apps_mode":appsMode,
            "apps":apps,
            "route_file":routeFiles,
            "reconnect":reconnectEnabled,
            "reconnect_retries":reconnectMaxRetries,
            "reconnect_base_delay":reconnectBaseDelaySeconds,
            "reconnect_max_delay":reconnectMaxDelaySeconds,
            "timeout":connectionTimeoutSeconds,
            "padding":paddingEnabled,
            "padding_min":paddingMin,
            "padding_max":paddingMax,
            "heartbeat":heartbeatEnabled,
            "heartbeat_interval":heartbeatIntervalMilliseconds,
            "heartbeat_size":heartbeatDataSize,
            "heartbeat_jitter":heartbeatJitterMilliseconds,
            "shaping":shapingEnabled,
            "shaping_gap_mean":shapingGapMeanMilliseconds,
            "shaping_gap_min":shapingGapMinMilliseconds,
            "shaping_gap_max":shapingGapMaxMilliseconds,
            "shaping_budget":shapingBudgetBytesPerSecond,
            "shaping_min_size":shapingMinSize,
            "shaping_max_size":shapingMaxSize,
            "shaping_stealth":shapingStealth,
            "shaping_stealth_mbps":shapingStealthRateMbps,
            "logging.level":loggingLevel ?? "",
            "logging.file":loggingFile ?? "",
            "logging.time_format":loggingTimeFormat ?? "",
        ]
        values["$routing_mode"]=routingMode
        for (key,value) in carriedKeys { values[key]=value }
        if let label { values["name"]=label }
        return try ConfigCore.call(["version":1,"op":op,"platform":"ios","source":nativeSource as Any? ?? NSNull(),"values":values,"unresolved":unparsedBooleanKeys+unparsedNumericKeys])
    }
    static func nativeImport(_ text: String) throws -> VPNConfig {
        let r = try ConfigCore.call(["version":1,"op":"import","source":text])
        guard let v=r["values"] as? [String:Any], let host=v["$host"] as? String, let port=v["$port"] as? Int else { throw VPNConfigError.invalid("Invalid native document") }
        var c=VPNConfig(serverAddress:host,port:port)
        c.nativeSource=r["source"] as? String
        c.protocolName=v["proto"] as! String
        c.username=v["user"] as! String
        c.password=v["pass"] as! String
        c.serverPublicKeyHex=(v["key"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.bindStaticToSession=v["bind_static"] as! Bool
        c.allowUnpinnedTofu=v["allow_unpinned_tofu"] as! Bool
        c.wireMode=v["mode"] as! String
        c.obfsKey=v["obfs_key"] as! String
        c.obfsFronting=v["front"] as! String
        c.sni=(v["sni"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.realityShortID=(v["reality_sid"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.quicEnabled=v["quic"] as! Bool
        c.awgEnabled=v["awg"] as! Bool
        c.awgJunkCount=v["jc"] as! Int
        c.awgJunkMin=v["jmin"] as! Int
        c.awgJunkMax=v["jmax"] as! Int
        c.mtu=v["mtu"] as! Int
        c.mtuProbe=v["mtu_probe"] as! Bool
        c.addDefaultGateway=v["gateway"] as! Bool
        c.ipv6Policy=v["ipv6"] as! String
        c.roamingPolicy=v["roaming"] as! String
        c.routeLocalNetworks=v["route_local"] as! Bool
        c.allowIPv4Leak=v["allow_ipv4_leak"] as! Bool
        c.allowIPv6Leak=v["allow_ipv6_leak"] as! Bool
        c.allowLAN=v["allow_lan"] as! Bool
        c.includeRoutes=v["include"] as! [String]
        c.excludeRoutes=v["exclude"] as! [String]
        c.dnsMode=v["dns"] as! String
        c.dnsServers=v["dns_servers"] as! [String]
        c.appsMode=v["apps_mode"] as! String
        c.apps=v["apps"] as! [String]
        c.routeFiles=v["route_file"] as! [String]
        c.reconnectEnabled=v["reconnect"] as! Bool
        c.reconnectMaxRetries=v["reconnect_retries"] as! Int
        c.reconnectBaseDelaySeconds=v["reconnect_base_delay"] as! Int
        c.reconnectMaxDelaySeconds=v["reconnect_max_delay"] as! Int
        c.connectionTimeoutSeconds=v["timeout"] as! Int
        c.paddingEnabled=v["padding"] as! Bool
        c.paddingMin=v["padding_min"] as! Int
        c.paddingMax=v["padding_max"] as! Int
        c.heartbeatEnabled=v["heartbeat"] as! Bool
        c.heartbeatIntervalMilliseconds=v["heartbeat_interval"] as! Int
        c.heartbeatDataSize=v["heartbeat_size"] as! Int
        c.heartbeatJitterMilliseconds=v["heartbeat_jitter"] as! Int
        c.shapingEnabled=v["shaping"] as! Bool
        c.shapingGapMeanMilliseconds=v["shaping_gap_mean"] as! Int
        c.shapingGapMinMilliseconds=v["shaping_gap_min"] as! Int
        c.shapingGapMaxMilliseconds=v["shaping_gap_max"] as! Int
        c.shapingBudgetBytesPerSecond=v["shaping_budget"] as! Int
        c.shapingMinSize=v["shaping_min_size"] as! Int
        c.shapingMaxSize=v["shaping_max_size"] as! Int
        c.shapingStealth=v["shaping_stealth"] as! Bool
        c.shapingStealthRateMbps=v["shaping_stealth_mbps"] as! Int
        c.loggingLevel=(v["logging.level"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.loggingFile=(v["logging.file"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.loggingTimeFormat=(v["logging.time_format"] as? String).flatMap { $0.isEmpty ? nil : $0 }
        c.routingMode=c.addDefaultGateway ? "full-tunnel" : "split-tunnel"
        let diagnostics=r["diagnostics"] as? [[String:Any]] ?? []
        func keys(_ code: String) -> [String] { diagnostics.filter { $0["code"] as? String == code }.compactMap { $0["key"] as? String } }
        c.unparsedBooleanKeys=keys("bool"); c.unparsedNumericKeys=keys("int"); c.unknownKeys=keys("unknown")
        c.duplicateKeys=keys("duplicate").map { $0.contains(".") ? $0 : "qeli." + $0 } + keys("section")
        for (key,raw) in r["raw"] as? [String:[String]] ?? [:] { if carriedINIKeys.contains(key) { c.carriedKeys[key]=raw.first ?? "" } }
        return c
    }
}

enum ConfigDefaults {
    static let protocolName: String = "tcp"
    static let username: String = "client"
    static let password: String = ""
    static let serverPublicKeyHex: String? = nil
    static let bindStaticToSession: Bool = true
    static let allowUnpinnedTofu: Bool = false
    static let wireMode: String = "fake-tls"
    static let obfsKey: String = ""
    static let obfsFronting: String = "websocket"
    static let sni: String? = nil
    static let realityShortID: String? = nil
    static let quicEnabled: Bool = false
    static let awgEnabled: Bool = false
    static let awgJunkCount: Int = 0
    static let awgJunkMin: Int = 40
    static let awgJunkMax: Int = 300
    static let mtu: Int = 0
    static let mtuProbe: Bool = true
    static let addDefaultGateway: Bool = true
    static let ipv6Policy: String = "auto"
    static let roamingPolicy: String = "auto"
    static let routeLocalNetworks: Bool = false
    static let allowIPv4Leak: Bool = false
    static let allowIPv6Leak: Bool = false
    static let allowLAN: Bool = false
    static let dnsMode: String = "tunnel"
    static let appsMode: String = "all"
    static let reconnectEnabled: Bool = true
    static let reconnectMaxRetries: Int = -1
    static let reconnectBaseDelaySeconds: Int = 1
    static let reconnectMaxDelaySeconds: Int = 60
    static let connectionTimeoutSeconds: Int = 30
    static let paddingEnabled: Bool = true
    static let paddingMin: Int = 0
    static let paddingMax: Int = 255
    static let heartbeatEnabled: Bool = true
    static let heartbeatIntervalMilliseconds: Int = 15000
    static let heartbeatDataSize: Int = 16
    static let heartbeatJitterMilliseconds: Int = 2000
    static let shapingEnabled: Bool = false
    static let shapingGapMeanMilliseconds: Int = 700
    static let shapingGapMinMilliseconds: Int = 40
    static let shapingGapMaxMilliseconds: Int = 6000
    static let shapingBudgetBytesPerSecond: Int = 16384
    static let shapingMinSize: Int = 64
    static let shapingMaxSize: Int = 1024
    static let shapingStealth: Bool = false
    static let shapingStealthRateMbps: Int = 2
    static let loggingLevel: String? = "info"
    static let loggingFile: String? = nil
    static let loggingTimeFormat: String? = "datetime"
}
