"""Generate model projections from the authoritative Rust editor schema (no parsing rules)."""
from pathlib import Path
import argparse, json, re
ROOT = Path(__file__).resolve().parents[1]
def generate():
    fields = [json.loads('['+m+']') for m in re.findall(r'field!\(([^\n]+)\)', (ROOT/'qeli/src/config/editor/schema.rs').read_text()) if m.startswith('"')]
    cs_source=(ROOT/'qeli-shared/QeliShared/Model/VpnConfig.cs').read_text(encoding='utf-8')
    kt_source=(ROOT/'qeli-android/app/src/main/kotlin/com/qeli/model/Config.kt').read_text(encoding='utf-8')
    sw_source=(ROOT/'qeli-ios/QeliCore/Model/VPNConfig.swift').read_text(encoding='utf-8')
    cs_types={name:kind.strip() for kind,name in re.findall(r'public\s+([\w<>?, ]+)\s+(\w+)\s*\{',cs_source)}
    kt_types={name:kind.strip() for name,kind in re.findall(r'val\s+(\w+):\s*([\w<>?]+)',kt_source)}
    optional_cs={'ServerPublicKeyHex','Sni','RealityShortId','LocalAddress','DevNode'}
    optional_sw=set(re.findall(r'var (\w+): String\?',sw_source))
    out={}
    cs=['// Generated by scripts/gen_config_bindings.py; change the Rust schema.', '#nullable enable', 'using System.Text.Json;', 'namespace Qeli.Shared.Model;', 'public sealed partial class VpnConfig {']
    carried=[f[0] for f in fields if f[3]=='-' and '.' not in f[0]]
    cs+=['    private static readonly HashSet<string> NativeCarriedKeys = new() { '+','.join(json.dumps(k) for k in carried)+' };']
    cs+=['    private Dictionary<string, object?> NativeValues() => new() {', '        ["$host"] = ServerAddress, ["$port"] = Port, ["$routing_mode"] = RoutingMode,']
    for key,kind,default,c,k,s in fields:
        if key=='server' or c=='-': continue
        val=c
        if key=='route_file': val='RouteFile is null ? AdditionalRouteFiles.ToArray() : new[] { RouteFile }.Concat(AdditionalRouteFiles).ToArray()'
        if kind=='string': val+=' ?? ""'
        cs+=['        ['+json.dumps(key)+'] = '+val+',']
    cs+=['    };', '    private JsonElement NativeOperation(string operation) {', '        var values = NativeValues();', '        foreach (var entry in CarriedKeys) values[entry.Key] = entry.Value;',
         '        return ConfigCore.Call(new { version=1, op=operation, source=NativeSource, values, unresolved=UnparsedBooleanKeys.Concat(UnparsedNumericKeys).ToArray() });', '    }',
         '    private static VpnConfig NativeImport(string text) {', '        var result = ConfigCore.Call(new { version=1, op="import", source=text });',
         '        var v = result.GetProperty("values");', '        var diagnostics = result.GetProperty("diagnostics").EnumerateArray().ToArray();',
         '        string[] Keys(string code) => diagnostics.Where(d => d.GetProperty("code").GetString() == code).Select(d => d.GetProperty("key").GetString()!).ToArray();',
         '        return new VpnConfig { NativeSource=result.GetProperty("source").GetString(), ServerAddress=v.GetProperty("$host").GetString()!, Port=v.GetProperty("$port").GetInt32(),']
    for key,kind,default,c,k,s in fields:
        if key=='server' or c=='-': continue
        get='v.GetProperty('+json.dumps(key)+')'
        if key=='route_file':
            cs+=['            RouteFile='+get+'.EnumerateArray().FirstOrDefault().GetString(),', '            AdditionalRouteFiles='+get+'.EnumerateArray().Skip(1).Select(x=>x.GetString()!).ToList(),']
            # default JsonElement.GetString throws for an empty array; helper below replaces it.
            continue
        t=cs_types.get(c,'string')
        val=get+'.Deserialize<'+t+'>()!'
        if c in optional_cs: val='('+get+'.GetString() is { Length: > 0 } '+c+'Value ? '+c+'Value : null)'
        cs+=['            '+c+' = '+val+',']
    cs+=['            RoutingMode=v.GetProperty("gateway").GetBoolean() ? "full-tunnel" : "split-tunnel",',
         '            UnparsedBooleanKeys=Keys("bool"), UnparsedNumericKeys=Keys("int"), UnknownKeys=Keys("unknown"),',
         '            DuplicateKeys=Keys("duplicate").Concat(Keys("section")).ToArray(),',
         '            CarriedKeys=result.GetProperty("raw").EnumerateObject().Where(p=>NativeCarriedKeys.Contains(p.Name)).ToDictionary(p=>p.Name,p=>p.Value[0].GetString()!),',
         '            InvalidRawValues=result.GetProperty("raw").EnumerateObject().Where(p=>diagnostics.Any(d=>d.GetProperty("key").GetString()==p.Name)).ToDictionary(p=>p.Name,p=>p.Value[0].GetString()!),', '        };', '    }', '}']
    cst='\n'.join(cs).replace('.EnumerateArray().FirstOrDefault().GetString()', '.EnumerateArray().Select(x=>x.GetString()).FirstOrDefault()')+'\n'
    out['qeli-shared/QeliShared/Model/VpnConfig.Native.g.cs']=cst
    kt=['// Generated by scripts/gen_config_bindings.py; change the Rust schema.', 'package com.qeli.model', 'import com.qeli.ConfigCore', 'import org.json.JSONObject', 'import org.json.JSONArray', 'internal object ConfigProjection {',
        '    private fun strings(a: JSONArray): List<String> = (0 until a.length()).map(a::getString)',
        '    fun operation(c: VpnConfig, op: String, label: String? = null): JSONObject {',
        '        val values = JSONObject().put("$host",c.serverAddress).put("$port",c.port)']
    # Escape Kotlin $ in literal service keys.
    kt[-1]=kt[-1].replace('"$','"\\$')
    for key,kind,default,c,k,s in fields:
        if key=='server' or k=='-': continue
        val='c.'+k
        if kind in ('list','lines'): val='JSONArray('+val+')'
        if kt_types.get(k,'').endswith('?'): val+=' ?: ""'
        kt+=['            .put('+json.dumps(key)+','+val+')']
    kt+=['        values.put("\\$routing_mode",c.routingMode)', '        c.carriedKeys.forEach { (key,value) -> values.put(key,value) }', '        if (label != null) values.put("name",label)',
         '        return ConfigCore.call(JSONObject().put("version",1).put("op",op).put("source",c.nativeSource ?: JSONObject.NULL).put("values",values).put("unresolved",JSONArray(c.unparsedBooleanKeys+c.unparsedNumericKeys)))', '    }',
         '    fun parse(text: String): VpnConfig {', '        val r = ConfigCore.call(JSONObject().put("version",1).put("op","import").put("source",text))',
         '        val v = r.getJSONObject("values")', '        val diagnostics = r.getJSONArray("diagnostics")',
         '        fun keys(code: String) = (0 until diagnostics.length()).map(diagnostics::getJSONObject).filter { it.getString("code")==code }.map { it.getString("key") }',
         '        val raw = r.getJSONObject("raw")', '        val carried = setOf('+','.join(json.dumps(f[0]) for f in fields if f[4]=='-' and '.' not in f[0])+')',
         '        return VpnConfig(serverAddress=v.getString("\\$host"),port=v.getInt("\\$port"),nativeSource=r.getString("source"),']
    for key,kind,default,c,k,s in fields:
        if key=='server' or k=='-':continue
        t=kt_types[k]
        get='v.'+('getBoolean' if kind=='bool' else 'getLong' if t=='Long' else 'getInt' if kind=='int' else 'getJSONArray' if kind in ('list','lines') else 'getString')+'('+json.dumps(key)+')'
        if kind in ('list','lines'): get='strings('+get+')'
        if t.endswith('?'): get+='.takeIf { it.isNotEmpty() }'
        kt+=['            '+k+'='+get+',']
    kt+=['            routingMode=if(v.getBoolean("gateway")) "full-tunnel" else "split-tunnel",',
         '            unparsedBooleanKeys=keys("bool"), unparsedNumericKeys=keys("int"), unknownKeys=keys("unknown"),',
         '            duplicateKeys=keys("duplicate").map { if (\'.\' in it) it else "qeli.$it" } + keys("section"),',
         '            carriedKeys=raw.keys().asSequence().filter { it in carried }.associateWith { raw.getJSONArray(it).getString(0) },', '        )', '    }', '}']
    out['qeli-android/app/src/main/kotlin/com/qeli/model/ConfigProjection.kt']='\n'.join(kt)+'\n'
    sw=['// Generated by scripts/gen_config_bindings.py; change the Rust schema.', 'import Foundation', 'extension VPNConfig {',
        '    static let carriedINIKeys: Set<String> = ['+','.join(json.dumps(f[0]) for f in fields if f[5]=='-' and '.' not in f[0])+']',
        '    func nativeOperation(_ op: String, label: String? = nil) throws -> [String: Any] {',
        '        var values: [String: Any] = ["$host":serverAddress, "$port":port,']
    for key,kind,default,c,k,s in fields:
        if key=='server' or s=='-': continue
        sw+=['            '+json.dumps(key)+':'+s+(' ?? ""' if s in optional_sw else '')+',']
    sw+=['        ]', '        values["$routing_mode"]=routingMode', '        for (key,value) in carriedKeys { values[key]=value }', '        if let label { values["name"]=label }',
         '        return try ConfigCore.call(["version":1,"op":op,"platform":"ios","source":nativeSource as Any? ?? NSNull(),"values":values,"unresolved":unparsedBooleanKeys+unparsedNumericKeys])', '    }',
         '    static func nativeImport(_ text: String) throws -> VPNConfig {', '        let r = try ConfigCore.call(["version":1,"op":"import","source":text])',
         '        guard let v=r["values"] as? [String:Any], let host=v["$host"] as? String, let port=v["$port"] as? Int else { throw VPNConfigError.invalid("Invalid native document") }',
         '        var c=VPNConfig(serverAddress:host,port:port)', '        c.nativeSource=r["source"] as? String']
    for key,kind,default,c,k,s in fields:
        if key=='server' or s=='-': continue
        t='Bool' if kind=='bool' else 'Int' if kind=='int' else '[String]' if kind in ('list','lines') else 'String'
        get='v['+json.dumps(key)+'] as! '+t
        if s in optional_sw: get='(v['+json.dumps(key)+'] as? String).flatMap { $0.isEmpty ? nil : $0 }'
        sw+=['        c.'+s+'='+get]
    sw+=['        c.routingMode=c.addDefaultGateway ? "full-tunnel" : "split-tunnel"',
         '        let diagnostics=r["diagnostics"] as? [[String:Any]] ?? []',
         '        func keys(_ code: String) -> [String] { diagnostics.filter { $0["code"] as? String == code }.compactMap { $0["key"] as? String } }',
         '        c.unparsedBooleanKeys=keys("bool"); c.unparsedNumericKeys=keys("int"); c.unknownKeys=keys("unknown")',
         '        c.duplicateKeys=keys("duplicate").map { $0.contains(".") ? $0 : "qeli." + $0 } + keys("section")',
         '        for (key,raw) in r["raw"] as? [String:[String]] ?? [:] { if carriedINIKeys.contains(key) { c.carriedKeys[key]=raw.first ?? "" } }',
         '        return c', '    }', '}']
    out['qeli-ios/QeliCore/Model/VPNConfigProjection.swift']='\n'.join(sw)+'\n'
    # Scalar defaults are emitted from the same Rust schema as the field mappings.
    # Model constructors refer to these constants, so a new profile cannot drift from import.
    defaults = [[], [], []]
    for key,kind,default,c,k,s in fields:
        if key == "server" or kind not in ("string", "int", "bool"): continue
        value = json.dumps(default) if kind == "string" else default
        if c != "-":
            t = cs_types[c]
            cv = "null" if t.endswith("?") and default == "" else value
            defaults[0].append(f"    public const {t} {c} = {cv};")
        if k != "-":
            t = kt_types[k]
            kv = "null" if t.endswith("?") and default == "" else value
            defaults[1].append(f"    {'val' if t.endswith('?') else 'const val'} {k}: {t} = {kv}")
        if s != "-":
            t = "Bool" if kind == "bool" else "Int" if kind == "int" else "String"
            if s in optional_sw: t += "?"
            sv = "nil" if t.endswith("?") and default == "" else value
            defaults[2].append(f"    static let {s}: {t} = {sv}")
    for path,head,body in zip(out, ["internal static class ConfigDefaults {", "internal object ConfigDefaults {", "enum ConfigDefaults {"], defaults):
        out[path] += "\n" + head + "\n" + "\n".join(body) + "\n}\n"
    # Explain model coverage separately from OS application. A missing typed property
    # is retained in nativeSource/carriedKeys, not rejected by a different parser.
    for lang in ("ru", "eng"):
        marker = "<!-- generated-model-coverage -->"
        end_marker = "<!-- /generated-model-coverage -->"
        path = f"docs/{lang}/reference/CLIENT-CONFIG-MATRIX.md"
        document = (ROOT/path).read_text(encoding="utf-8")
        groups = {}
        for field in fields:
            shape = tuple("M" if p != "-" else "S" for p in field[3:])
            groups.setdefault(shape, []).append(field[0])
        counts = [sum(f[i] != "-" for f in fields) for i in (3,4,5)]
        if lang == "ru":
            lines = ["## Покрытие моделей: все 84 поля", "",
                "Этот блок генерируется из `editor/schema.rs`; M — типизированное свойство модели,",
                "S — значение сохраняется в исходном документе ядра и/или `carriedKeys`.",
                "Это не перечень контролов формы: поле без отдельного UI остаётся доступно через INI.",
                "Все 81 ключ `[qeli]` и 3 ключа `[logging]` распознаются общим парсером.", "",
                f"Ключей с типизированным представлением: C# {counts[0]}, Kotlin {counts[1]}, Swift {counts[2]}; остальные поля сохраняются как S.", "",
                "| Ключи схемы | C# (Windows/macOS) | Kotlin | Swift |", "|---|:-:|:-:|:-:|"]
        else:
            lines = ["## Model coverage: all 84 fields", "",
                "This block is generated from `editor/schema.rs`: M is a typed model property;",
                "S is preserved in the core source document and/or `carriedKeys`.",
                "This is not a form-control inventory: fields without a dedicated UI remain available through INI.",
                "All 81 `[qeli]` keys and 3 `[logging]` keys are recognized by the shared parser.", "",
                f"Keys mapped to typed properties: C# {counts[0]}, Kotlin {counts[1]}, Swift {counts[2]}; remaining fields are preserved as S.", "",
                "| Schema keys | C# (Windows/macOS) | Kotlin | Swift |", "|---|:-:|:-:|:-:|"]
        for shape, keys in groups.items():
            lines.append("| " + " ".join(f"`{key}`" for key in keys) + " | " + " | ".join(shape) + " |")
        block = marker + "\n" + "\n".join(lines) + "\n" + end_marker
        if marker in document:
            before, rest = document.split(marker,1)
            _, after = rest.split(end_marker,1)
            document = before + block + after
        else:
            document = document.rstrip() + "\n\n" + block + "\n"
        out[path] = document
    return out
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    for name,text in generate().items():
        p=ROOT/name
        if args.check:
            if not p.exists() or p.read_text(encoding='utf-8')!=text: raise SystemExit('Stale generated projection: '+name)
        else:p.write_text(text,encoding='utf-8')
