// Generated by scripts/gen_config_bindings.py; change the Rust schema.
package com.qeli.model
import com.qeli.ConfigCore
import org.json.JSONObject
import org.json.JSONArray
internal object ConfigProjection {
    private fun strings(a: JSONArray): List<String> = (0 until a.length()).map(a::getString)
    fun operation(c: VpnConfig, op: String, label: String? = null): JSONObject {
        val values = JSONObject().put("\$host",c.serverAddress).put("\$port",c.port)
            .put("proto",c.protocol)
            .put("user",c.username)
            .put("pass",c.password)
            .put("key",c.serverPublicKeyHex ?: "")
            .put("bind_static",c.bindStaticToSession)
            .put("allow_unpinned_tofu",c.allowUnpinnedTofu)
            .put("mode",c.wireMode)
            .put("obfs_key",c.obfsKey)
            .put("front",c.obfsFronting)
            .put("sni",c.sni ?: "")
            .put("reality_sid",c.realityShortId ?: "")
            .put("quic",c.quicEnabled)
            .put("awg",c.awgEnabled)
            .put("jc",c.awgJc)
            .put("jmin",c.awgJmin)
            .put("jmax",c.awgJmax)
            .put("mtu",c.mtu)
            .put("mtu_probe",c.mtuProbe)
            .put("gateway",c.addDefaultGateway)
            .put("ipv6",c.ipv6)
            .put("roaming",c.roaming)
            .put("route_local",c.routeLocalNetworks)
            .put("kill_switch",c.killSwitch)
            .put("allow_ipv4_leak",c.allowIpv4Leak)
            .put("allow_ipv6_leak",c.allowIpv6Leak)
            .put("allow_lan",c.allowLan)
            .put("include",JSONArray(c.includeRoutes))
            .put("exclude",JSONArray(c.excludeRoutes))
            .put("dns",c.dnsMode)
            .put("dns_servers",JSONArray(c.dnsServers))
            .put("apps_mode",c.appsMode)
            .put("apps",JSONArray(c.apps))
            .put("route_file",JSONArray(c.routeFiles))
            .put("reconnect",c.reconnectEnabled)
            .put("reconnect_retries",c.reconnectMaxRetries)
            .put("reconnect_base_delay",c.reconnectBaseDelaySecs)
            .put("reconnect_max_delay",c.reconnectMaxDelaySecs)
            .put("timeout",c.connectionTimeoutSecs)
            .put("padding",c.paddingEnabled)
            .put("padding_min",c.paddingMin)
            .put("padding_max",c.paddingMax)
            .put("heartbeat",c.heartbeatEnabled)
            .put("heartbeat_interval",c.heartbeatIntervalMs)
            .put("heartbeat_size",c.heartbeatDataSize)
            .put("heartbeat_jitter",c.heartbeatJitterMs)
            .put("shaping",c.shapingEnabled)
            .put("shaping_gap_mean",c.shapingGapMeanMs)
            .put("shaping_gap_min",c.shapingGapMinMs)
            .put("shaping_gap_max",c.shapingGapMaxMs)
            .put("shaping_budget",c.shapingBudgetBytesPerSec)
            .put("shaping_min_size",c.shapingMinSize)
            .put("shaping_max_size",c.shapingMaxSize)
            .put("shaping_stealth",c.shapingStealth)
            .put("shaping_stealth_mbps",c.shapingStealthRateMbps)
            .put("logging.level",c.loggingLevel ?: "")
            .put("logging.file",c.loggingFile ?: "")
            .put("logging.time_format",c.loggingTimeFormat ?: "")
        values.put("\$routing_mode",c.routingMode)
        c.carriedKeys.forEach { (key,value) -> values.put(key,value) }
        if (label != null) values.put("name",label)
        return ConfigCore.call(JSONObject().put("version",1).put("op",op).put("source",c.nativeSource ?: JSONObject.NULL).put("values",values).put("unresolved",JSONArray(c.unparsedBooleanKeys+c.unparsedNumericKeys)))
    }
    fun parse(text: String): VpnConfig {
        val r = ConfigCore.call(JSONObject().put("version",1).put("op","import").put("source",text))
        val v = r.getJSONObject("values")
        val diagnostics = r.getJSONArray("diagnostics")
        fun keys(code: String) = (0 until diagnostics.length()).map(diagnostics::getJSONObject).filter { it.getString("code")==code }.map { it.getString("key") }
        val raw = r.getJSONObject("raw")
        val carried = setOf("name","persist_tun","forward","local","lport","metric","dev_node","dev","device_type","dev_attach","autostart","exit_node","gateway_nat","lan_subnet","lan_subnet_ipv6","post_up","post_down","password_file","password_command","keepalive","tcp_nodelay","recv_buffer_size","send_buffer_size","reality_compact","reality_split","reality_split_delay")
        return VpnConfig(serverAddress=v.getString("\$host"),port=v.getInt("\$port"),nativeSource=r.getString("source"),
            protocol=v.getString("proto"),
            username=v.getString("user"),
            password=v.getString("pass"),
            serverPublicKeyHex=v.getString("key").takeIf { it.isNotEmpty() },
            bindStaticToSession=v.getBoolean("bind_static"),
            allowUnpinnedTofu=v.getBoolean("allow_unpinned_tofu"),
            wireMode=v.getString("mode"),
            obfsKey=v.getString("obfs_key"),
            obfsFronting=v.getString("front"),
            sni=v.getString("sni").takeIf { it.isNotEmpty() },
            realityShortId=v.getString("reality_sid").takeIf { it.isNotEmpty() },
            quicEnabled=v.getBoolean("quic"),
            awgEnabled=v.getBoolean("awg"),
            awgJc=v.getInt("jc"),
            awgJmin=v.getInt("jmin"),
            awgJmax=v.getInt("jmax"),
            mtu=v.getInt("mtu"),
            mtuProbe=v.getBoolean("mtu_probe"),
            addDefaultGateway=v.getBoolean("gateway"),
            ipv6=v.getString("ipv6"),
            roaming=v.getString("roaming"),
            routeLocalNetworks=v.getBoolean("route_local"),
            killSwitch=v.getBoolean("kill_switch"),
            allowIpv4Leak=v.getBoolean("allow_ipv4_leak"),
            allowIpv6Leak=v.getBoolean("allow_ipv6_leak"),
            allowLan=v.getBoolean("allow_lan"),
            includeRoutes=strings(v.getJSONArray("include")),
            excludeRoutes=strings(v.getJSONArray("exclude")),
            dnsMode=v.getString("dns"),
            dnsServers=strings(v.getJSONArray("dns_servers")),
            appsMode=v.getString("apps_mode"),
            apps=strings(v.getJSONArray("apps")),
            routeFiles=strings(v.getJSONArray("route_file")),
            reconnectEnabled=v.getBoolean("reconnect"),
            reconnectMaxRetries=v.getInt("reconnect_retries"),
            reconnectBaseDelaySecs=v.getLong("reconnect_base_delay"),
            reconnectMaxDelaySecs=v.getLong("reconnect_max_delay"),
            connectionTimeoutSecs=v.getLong("timeout"),
            paddingEnabled=v.getBoolean("padding"),
            paddingMin=v.getInt("padding_min"),
            paddingMax=v.getInt("padding_max"),
            heartbeatEnabled=v.getBoolean("heartbeat"),
            heartbeatIntervalMs=v.getLong("heartbeat_interval"),
            heartbeatDataSize=v.getInt("heartbeat_size"),
            heartbeatJitterMs=v.getLong("heartbeat_jitter"),
            shapingEnabled=v.getBoolean("shaping"),
            shapingGapMeanMs=v.getLong("shaping_gap_mean"),
            shapingGapMinMs=v.getLong("shaping_gap_min"),
            shapingGapMaxMs=v.getLong("shaping_gap_max"),
            shapingBudgetBytesPerSec=v.getInt("shaping_budget"),
            shapingMinSize=v.getInt("shaping_min_size"),
            shapingMaxSize=v.getInt("shaping_max_size"),
            shapingStealth=v.getBoolean("shaping_stealth"),
            shapingStealthRateMbps=v.getInt("shaping_stealth_mbps"),
            loggingLevel=v.getString("logging.level").takeIf { it.isNotEmpty() },
            loggingFile=v.getString("logging.file").takeIf { it.isNotEmpty() },
            loggingTimeFormat=v.getString("logging.time_format").takeIf { it.isNotEmpty() },
            routingMode=if(v.getBoolean("gateway")) "full-tunnel" else "split-tunnel",
            unparsedBooleanKeys=keys("bool"), unparsedNumericKeys=keys("int"), unknownKeys=keys("unknown"),
            duplicateKeys=keys("duplicate").map { if ('.' in it) it else "qeli.$it" } + keys("section"),
            carriedKeys=raw.keys().asSequence().filter { it in carried }.associateWith { raw.getJSONArray(it).getString(0) },
        )
    }
}

internal object ConfigDefaults {
    const val protocol: String = "tcp"
    const val username: String = "client"
    const val password: String = ""
    val serverPublicKeyHex: String? = null
    const val bindStaticToSession: Boolean = true
    const val allowUnpinnedTofu: Boolean = false
    const val wireMode: String = "fake-tls"
    const val obfsKey: String = ""
    const val obfsFronting: String = "websocket"
    val sni: String? = null
    val realityShortId: String? = null
    const val quicEnabled: Boolean = false
    const val awgEnabled: Boolean = false
    const val awgJc: Int = 0
    const val awgJmin: Int = 40
    const val awgJmax: Int = 300
    const val mtu: Int = 0
    const val mtuProbe: Boolean = true
    const val addDefaultGateway: Boolean = true
    const val ipv6: String = "auto"
    const val roaming: String = "auto"
    const val routeLocalNetworks: Boolean = false
    const val killSwitch: Boolean = false
    const val allowIpv4Leak: Boolean = false
    const val allowIpv6Leak: Boolean = false
    const val allowLan: Boolean = false
    const val dnsMode: String = "tunnel"
    const val appsMode: String = "all"
    const val reconnectEnabled: Boolean = true
    const val reconnectMaxRetries: Int = -1
    const val reconnectBaseDelaySecs: Long = 1
    const val reconnectMaxDelaySecs: Long = 60
    const val connectionTimeoutSecs: Long = 30
    const val paddingEnabled: Boolean = true
    const val paddingMin: Int = 0
    const val paddingMax: Int = 255
    const val heartbeatEnabled: Boolean = true
    const val heartbeatIntervalMs: Long = 15000
    const val heartbeatDataSize: Int = 16
    const val heartbeatJitterMs: Long = 2000
    const val shapingEnabled: Boolean = false
    const val shapingGapMeanMs: Long = 700
    const val shapingGapMinMs: Long = 40
    const val shapingGapMaxMs: Long = 6000
    const val shapingBudgetBytesPerSec: Int = 16384
    const val shapingMinSize: Int = 64
    const val shapingMaxSize: Int = 1024
    const val shapingStealth: Boolean = false
    const val shapingStealthRateMbps: Int = 2
    val loggingLevel: String? = "info"
    val loggingFile: String? = null
    val loggingTimeFormat: String? = "datetime"
}
